In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
%matplotlib inline

# New Section

# New Section

In [ ]:
dataset = pd.read_csv('/content/sample_data/breast cancer data.csv')
dataset.head()

         id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0    842302         M  ...          0.4601                  0.11890
1    842517         M  ...          0.2750                  0.08902
2  84300903         M  ...          0.3613                  0.08758
3  84348301         M  ...          0.6638                  0.17300
4  84358402         M  ...          0.2364                  0.07678

[5 rows x 32 columns]

In [ ]:
def diagnosis(x):
    if x=='M' :
        return 1
    if x=='B' :
        return 0
dataset['diagnosis'] = dataset['diagnosis'].apply(diagnosis)
print(dataset)

           id  diagnosis  ...  symmetry_worst  fractal_dimension_worst
0      842302          1  ...          0.4601                  0.11890
1      842517          1  ...          0.2750                  0.08902
2    84300903          1  ...          0.3613                  0.08758
3    84348301          1  ...          0.6638                  0.17300
4    84358402          1  ...          0.2364                  0.07678
..        ...        ...  ...             ...                      ...
564    926424          1  ...          0.2060                  0.07115
565    926682          1  ...          0.2572                  0.06637
566    926954          1  ...          0.2218                  0.07820
567    927241          1  ...          0.4087                  0.12400
568     92751          0  ...          0.2871                  0.07039

[569 rows x 32 columns]

In [ ]:
print("Any missing sample in data set:",dataset.isnull().values.any(), "\n")

Any missing sample in data set: False

In [ ]:
#replace missing value with mean
dataset = dataset.replace([np.inf, -np.inf], np.nan)
dataset= dataset.fillna(dataset.mean())
dataset

           id  diagnosis  ...  symmetry_worst  fractal_dimension_worst
0      842302          1  ...          0.4601                  0.11890
1      842517          1  ...          0.2750                  0.08902
2    84300903          1  ...          0.3613                  0.08758
3    84348301          1  ...          0.6638                  0.17300
4    84358402          1  ...          0.2364                  0.07678
..        ...        ...  ...             ...                      ...
564    926424          1  ...          0.2060                  0.07115
565    926682          1  ...          0.2572                  0.06637
566    926954          1  ...          0.2218                  0.07820
567    927241          1  ...          0.4087                  0.12400
568     92751          0  ...          0.2871                  0.07039

[569 rows x 32 columns]

In [ ]:
#drop this column because it's not necessary (null)
#dataset= dataset.drop(columns=["Unnamed: 5"])
print(dataset)

           id  diagnosis  ...  symmetry_worst  fractal_dimension_worst
0      842302          1  ...          0.4601                  0.11890
1      842517          1  ...          0.2750                  0.08902
2    84300903          1  ...          0.3613                  0.08758
3    84348301          1  ...          0.6638                  0.17300
4    84358402          1  ...          0.2364                  0.07678
..        ...        ...  ...             ...                      ...
564    926424          1  ...          0.2060                  0.07115
565    926682          1  ...          0.2572                  0.06637
566    926954          1  ...          0.2218                  0.07820
567    927241          1  ...          0.4087                  0.12400
568     92751          0  ...          0.2871                  0.07039

[569 rows x 32 columns]

In [ ]:
Y = dataset['diagnosis']
X = dataset.drop(columns=['diagnosis'])
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=9)
print('X train shape: ', X_train.shape)
print('Y train shape: ', Y_train.shape)
print('X test shape: ', X_test.shape)
print('Y test shape: ', Y_test.shape)

X train shape:  (455, 31)
Y train shape:  (455,)
X test shape:  (114, 31)
Y test shape:  (114,)

In [ ]:
svc_classifier= SVC(kernel='rbf')
svc_classifier

SVC()

In [ ]:
svc_classifier=svc_classifier.fit(X_train,Y_train)

In [ ]:
y_pred=svc_classifier.predict(X_test)

In [ ]:
print(confusion_matrix(Y_test,y_pred))

[[74  0]
 [40  0]]

In [ ]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.65      1.00      0.79        74
           1       0.00      0.00      0.00        40

    accuracy                           0.65       114
   macro avg       0.32      0.50      0.39       114
weighted avg       0.42      0.65      0.51       114

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))